### ISSUE TITLE
Feature request: settings toggle to not rotate direction indicator automatically on move

### ISSUE THREAD

**Issue by Exxar** [mclemente/about-face#15]
Would it be possible to introduce an option in module settings, which when toggled, would "lock" the directional indicator when we move the tokens? The idea is to only have indicators rotate manually through player input, and not when the tokens move.

We play GURPS which uses a hex grid and facing is very important, and most of the time when we move tokens we move them in such a way that they should retain their original facing between the initial and final positions. However, the indicator gets turned around and we have to rotate it at the end of movement each time which wastes a lot of time for us.

**Comment by mclemente** [comment]
Hey, the good news is that I've added a setting to it. The bad news is that it's only for Foundry v9, since I've started to port my modules over to it, so you might be a few months away from it.

For now, if you want to disable the rotation you can go to the scripts/logic.js file and delete these lines: https://github.com/mclemente/about-face/blob/v3.7/scripts/logic.js#L107-L122, which will have the same effect as the change.
