### ISSUE TITLE
Token direction resets when changing token status

### ISSUE THREAD

**Issue by guillaume-gc** [mclemente/about-face#57]
When adding a status to a token or hiding it, the token resets to its default position.

Before adding status:
![image](https://user-images.githubusercontent.com/15614283/201489581-ebadb196-0705-46a8-b0fb-9b8b64d3abe9.png)

After adding status (token default position is facing bottom):
![image](https://user-images.githubusercontent.com/15614283/201489604-4a2b7c33-e031-4aa2-80d0-da70b308ffde.png)

The problems appears even if all my modules are disabled except `about-face` and `libWrapper`.

I'm playing on the PF1e system, unsure if it's related.

**Comment by mclemente** [comment]
I can't reproduce this. Any errors on the console?

**Comment by tianevitt** [comment]
I can confirm this issue. The best way to reproduce it is to enter a combat state, have the character take some action, and then proceed to the next character. It also seems to happen after a character takes damage.

The above poster summarized it well; it seems to happen when the character status changes in any way.

Love this mod otherwise, so I hop you can figure it out! :)

**Comment by R0TEAM** [comment]
the same problem as I described in #56
this make the module pointless, as instead of limiting the visible information to a defined arc and facing, it rotates often so the player anyway see all .... and you cant say after this happen (to many situation where this bug is triggered) > please forgot what you have seen ....

**Comment by guillaume-gc** [comment]
Thanks for the fast reply @mclemente ! Your module is great !

I don't have any error on the console.

Personally I don't need to do anything complex. I just launch Foundry on a PF1e system, rotate a token and then set a status or make a token invisible, and it resets its rotation.

**Comment by mclemente** [comment]
Thanks to everyone for the inputs. I managed to figure out what was happening and you can just update and that behavior will be gone.
There was a bug in About Face that it would try to change the token's rotation on updates that had no rotation in them. So it would return a NaN value and reset to 0.
