### ISSUE TITLE
Getting the tool to work on a scene

### ISSUE THREAD

**Issue by HippyCraig** [mclemente/about-face#61]
Does the tool differentiate between token types and if so how?  When I enabled it for this scene the round token only flips horizontaly but the other one rotates based on the direction, this is something that I did not set specificly

![image](https://user-images.githubusercontent.com/17074456/202830297-51910d12-094b-47fd-9e02-7357c78fcc80.png)

Another question even though I enabled this mod it didnt work on the scene until I went inot the scene config and enabled it.  It wasnt intuitive to know that had to be done.  Is that the right behavoir?

**Comment by HippyCraig** [comment]
I would also like to add that the Scene had the enable on by default but I had to check and uncheck it to get it to take

**Comment by mclemente** [comment]
>Does the tool differentiate between token types and if so how?

There's no diferentiation. Both should follow the global setting (Mirror Horizontally by default). You can check it on each token's configuration, on the About Face tab.

>even though I enabled this mod it didnt work on the scene until I went inot the scene config and enabled it.

Every scene has it enabled by default. I don't know what else to tell you, because that part of the module is pretty straightforward and my tests don't show anything different (e.g. create a scene with the module disabled, add tokens, then enable the module).

**Comment by HippyCraig** [comment]
In my case the scenes were there already before enabling the module.  I had to uncheck and recheck for that to work in those case.  As for the Mirroring, I didnt change any setting but the two tokens behaved differntly without intevention, the top down one on the right would rotate depending the the direction I moved the token.  The one on the left would only flip horizontialy when moveing around the screen as if it was smart enough to figure out what type of token image was there, that was the reason for the question.
