### ISSUE TITLE
Bug about face and sequencer

### ISSUE THREAD

**Issue by Fridan99** [mclemente/about-face#71]
foundry v10.291

system dnd5e 2.1.5

about face 3.23

sequencer 2.412

dae 0.10.32

midi 10.0.32

i’m trying to make an animated shield effect, in which per DAE it adds +2 AC for 1 minute (system.attributes.ac.bonus...add..+2), active effect.

The extra bonus is not applied correctly, and I get this error message on the console. 

![A302EED1-5402-417E-AA63-20A8543BCC78](https://user-images.githubusercontent.com/86131373/222963967-7476eac5-34fc-4b8a-a216-67fea3b6d078.jpeg)

**Comment by mclemente** [comment]
That error alone is inconclusive, unfortunately. The function that draws the arrow is breaking somewhere, but that error on the console is the actual error handler trying to get the token's name and failing.
Even if a token has no name, it should still return its actor's name, so I'm not sure how that's breaking. I can't tell exactly what the error is, but I'd guess it's related to the token's data not returning a name, since that shouldn't be happening.
Does that token has a Represented Actor? Or is it set to None?

**Comment by Fridan99** [comment]
Is an owned actor (linked). Whatever you need to locate the bug, let me know and I will provide you with or do the necessary tests.

**Comment by mclemente** [comment]
That error is only on that token, right? Can you export its actor's data and send it over here?

**Comment by Fridan99** [comment]
Sure..... 

https://files.fm/u/nnkbtrgca  (the actor is here) :)

**Comment by mclemente** [comment]
With just About Face enabled, the error isn't present on the token and setting an active effect like the one you mentioned didn't break it either.
I'm confident this issue isn't caused by About Face, it just got caught in the crossfire since the token's data is being "broken" somewhere in-between the Hook call and the function. Try setting the active effect with just About Face enabled and it shouldn't throw any errors.
